// Auto-generated. Do not edit!

// (in-package controller_adaptiveclbf.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TrainModelResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.model_trained = null;
    }
    else {
      if (initObj.hasOwnProperty('model_trained')) {
        this.model_trained = initObj.model_trained
      }
      else {
        this.model_trained = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TrainModelResult
    // Serialize message field [model_trained]
    bufferOffset = _serializer.bool(obj.model_trained, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TrainModelResult
    let len;
    let data = new TrainModelResult(null);
    // Deserialize message field [model_trained]
    data.model_trained = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'controller_adaptiveclbf/TrainModelResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '188271f01225083e18f9147e2957a5e5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # result definition
    bool model_trained
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TrainModelResult(null);
    if (msg.model_trained !== undefined) {
      resolved.model_trained = msg.model_trained;
    }
    else {
      resolved.model_trained = false
    }

    return resolved;
    }
};

module.exports = TrainModelResult;
