// Generated by gencpp from file controller_adaptiveclbf/AddData2Model.msg
// DO NOT EDIT!


#ifndef CONTROLLER_ADAPTIVECLBF_MESSAGE_ADDDATA2MODEL_H
#define CONTROLLER_ADAPTIVECLBF_MESSAGE_ADDDATA2MODEL_H

#include <ros/service_traits.h>


#include <controller_adaptiveclbf/AddData2ModelRequest.h>
#include <controller_adaptiveclbf/AddData2ModelResponse.h>


namespace controller_adaptiveclbf
{

struct AddData2Model
{

typedef AddData2ModelRequest Request;
typedef AddData2ModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddData2Model
} // namespace controller_adaptiveclbf


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controller_adaptiveclbf::AddData2Model > {
  static const char* value()
  {
    return "076f3cf7844dd31ef610e184f70f26b5";
  }

  static const char* value(const ::controller_adaptiveclbf::AddData2Model&) { return value(); }
};

template<>
struct DataType< ::controller_adaptiveclbf::AddData2Model > {
  static const char* value()
  {
    return "controller_adaptiveclbf/AddData2Model";
  }

  static const char* value(const ::controller_adaptiveclbf::AddData2Model&) { return value(); }
};


// service_traits::MD5Sum< ::controller_adaptiveclbf::AddData2ModelRequest> should match
// service_traits::MD5Sum< ::controller_adaptiveclbf::AddData2Model >
template<>
struct MD5Sum< ::controller_adaptiveclbf::AddData2ModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controller_adaptiveclbf::AddData2Model >::value();
  }
  static const char* value(const ::controller_adaptiveclbf::AddData2ModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller_adaptiveclbf::AddData2ModelRequest> should match
// service_traits::DataType< ::controller_adaptiveclbf::AddData2Model >
template<>
struct DataType< ::controller_adaptiveclbf::AddData2ModelRequest>
{
  static const char* value()
  {
    return DataType< ::controller_adaptiveclbf::AddData2Model >::value();
  }
  static const char* value(const ::controller_adaptiveclbf::AddData2ModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controller_adaptiveclbf::AddData2ModelResponse> should match
// service_traits::MD5Sum< ::controller_adaptiveclbf::AddData2Model >
template<>
struct MD5Sum< ::controller_adaptiveclbf::AddData2ModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controller_adaptiveclbf::AddData2Model >::value();
  }
  static const char* value(const ::controller_adaptiveclbf::AddData2ModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller_adaptiveclbf::AddData2ModelResponse> should match
// service_traits::DataType< ::controller_adaptiveclbf::AddData2Model >
template<>
struct DataType< ::controller_adaptiveclbf::AddData2ModelResponse>
{
  static const char* value()
  {
    return DataType< ::controller_adaptiveclbf::AddData2Model >::value();
  }
  static const char* value(const ::controller_adaptiveclbf::AddData2ModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLER_ADAPTIVECLBF_MESSAGE_ADDDATA2MODEL_H
