// Generated by gencpp from file controller_adaptiveclbf/PredictModel.msg
// DO NOT EDIT!


#ifndef CONTROLLER_ADAPTIVECLBF_MESSAGE_PREDICTMODEL_H
#define CONTROLLER_ADAPTIVECLBF_MESSAGE_PREDICTMODEL_H

#include <ros/service_traits.h>


#include <controller_adaptiveclbf/PredictModelRequest.h>
#include <controller_adaptiveclbf/PredictModelResponse.h>


namespace controller_adaptiveclbf
{

struct PredictModel
{

typedef PredictModelRequest Request;
typedef PredictModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PredictModel
} // namespace controller_adaptiveclbf


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controller_adaptiveclbf::PredictModel > {
  static const char* value()
  {
    return "c5234f87cf246f56b768d599ee6e3db3";
  }

  static const char* value(const ::controller_adaptiveclbf::PredictModel&) { return value(); }
};

template<>
struct DataType< ::controller_adaptiveclbf::PredictModel > {
  static const char* value()
  {
    return "controller_adaptiveclbf/PredictModel";
  }

  static const char* value(const ::controller_adaptiveclbf::PredictModel&) { return value(); }
};


// service_traits::MD5Sum< ::controller_adaptiveclbf::PredictModelRequest> should match
// service_traits::MD5Sum< ::controller_adaptiveclbf::PredictModel >
template<>
struct MD5Sum< ::controller_adaptiveclbf::PredictModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controller_adaptiveclbf::PredictModel >::value();
  }
  static const char* value(const ::controller_adaptiveclbf::PredictModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller_adaptiveclbf::PredictModelRequest> should match
// service_traits::DataType< ::controller_adaptiveclbf::PredictModel >
template<>
struct DataType< ::controller_adaptiveclbf::PredictModelRequest>
{
  static const char* value()
  {
    return DataType< ::controller_adaptiveclbf::PredictModel >::value();
  }
  static const char* value(const ::controller_adaptiveclbf::PredictModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controller_adaptiveclbf::PredictModelResponse> should match
// service_traits::MD5Sum< ::controller_adaptiveclbf::PredictModel >
template<>
struct MD5Sum< ::controller_adaptiveclbf::PredictModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controller_adaptiveclbf::PredictModel >::value();
  }
  static const char* value(const ::controller_adaptiveclbf::PredictModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller_adaptiveclbf::PredictModelResponse> should match
// service_traits::DataType< ::controller_adaptiveclbf::PredictModel >
template<>
struct DataType< ::controller_adaptiveclbf::PredictModelResponse>
{
  static const char* value()
  {
    return DataType< ::controller_adaptiveclbf::PredictModel >::value();
  }
  static const char* value(const ::controller_adaptiveclbf::PredictModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLER_ADAPTIVECLBF_MESSAGE_PREDICTMODEL_H
