// Generated by gencpp from file controller_adaptiveclbf/TrainModelResult.msg
// DO NOT EDIT!


#ifndef CONTROLLER_ADAPTIVECLBF_MESSAGE_TRAINMODELRESULT_H
#define CONTROLLER_ADAPTIVECLBF_MESSAGE_TRAINMODELRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller_adaptiveclbf
{
template <class ContainerAllocator>
struct TrainModelResult_
{
  typedef TrainModelResult_<ContainerAllocator> Type;

  TrainModelResult_()
    : model_trained(false)  {
    }
  TrainModelResult_(const ContainerAllocator& _alloc)
    : model_trained(false)  {
  (void)_alloc;
    }



   typedef uint8_t _model_trained_type;
  _model_trained_type model_trained;





  typedef boost::shared_ptr< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> const> ConstPtr;

}; // struct TrainModelResult_

typedef ::controller_adaptiveclbf::TrainModelResult_<std::allocator<void> > TrainModelResult;

typedef boost::shared_ptr< ::controller_adaptiveclbf::TrainModelResult > TrainModelResultPtr;
typedef boost::shared_ptr< ::controller_adaptiveclbf::TrainModelResult const> TrainModelResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator1> & lhs, const ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator2> & rhs)
{
  return lhs.model_trained == rhs.model_trained;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator1> & lhs, const ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller_adaptiveclbf

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "188271f01225083e18f9147e2957a5e5";
  }

  static const char* value(const ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x188271f01225083eULL;
  static const uint64_t static_value2 = 0x18f9147e2957a5e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller_adaptiveclbf/TrainModelResult";
  }

  static const char* value(const ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"bool model_trained\n"
;
  }

  static const char* value(const ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_trained);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrainModelResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller_adaptiveclbf::TrainModelResult_<ContainerAllocator>& v)
  {
    s << indent << "model_trained: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.model_trained);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_ADAPTIVECLBF_MESSAGE_TRAINMODELRESULT_H
