// Generated by gencpp from file controller_adaptiveclbf/TrainModelFeedback.msg
// DO NOT EDIT!


#ifndef CONTROLLER_ADAPTIVECLBF_MESSAGE_TRAINMODELFEEDBACK_H
#define CONTROLLER_ADAPTIVECLBF_MESSAGE_TRAINMODELFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller_adaptiveclbf
{
template <class ContainerAllocator>
struct TrainModelFeedback_
{
  typedef TrainModelFeedback_<ContainerAllocator> Type;

  TrainModelFeedback_()
    {
    }
  TrainModelFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TrainModelFeedback_

typedef ::controller_adaptiveclbf::TrainModelFeedback_<std::allocator<void> > TrainModelFeedback;

typedef boost::shared_ptr< ::controller_adaptiveclbf::TrainModelFeedback > TrainModelFeedbackPtr;
typedef boost::shared_ptr< ::controller_adaptiveclbf::TrainModelFeedback const> TrainModelFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace controller_adaptiveclbf

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller_adaptiveclbf/TrainModelFeedback";
  }

  static const char* value(const ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback definition\n"
"\n"
;
  }

  static const char* value(const ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrainModelFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::controller_adaptiveclbf::TrainModelFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_ADAPTIVECLBF_MESSAGE_TRAINMODELFEEDBACK_H
