(cl:in-package controller_adaptiveclbf-msg)
(cl:export '(HEADER-VAL
          HEADER
          LATENCY-VAL
          LATENCY
          DT-VAL
          DT
          HEADING-VAL
          HEADING
          VEL_X_BODY-VAL
          VEL_X_BODY
          VEL_Y_BODY-VAL
          VEL_Y_BODY
          Z-VAL
          Z
          Z_REF-VAL
          Z_REF
          Z_DOT-VAL
          Z_DOT
          Y_OUT-VAL
          Y_OUT
          MU_RM-VAL
          MU_RM
          MU_PD-VAL
          MU_PD
          MU_AD-VAL
          MU_AD
          MU_MODEL-VAL
          MU_MODEL
          RHO-VAL
          RHO
          MU_QP-VAL
          MU_QP
          MU-VAL
          MU
          U_NEW-VAL
          U_NEW
          U_UNSAT-VAL
          U_UNSAT
          TRUEDELTA-VAL
          TRUEDELTA
          TRUE_PREDICT_ERROR-VAL
          TRUE_PREDICT_ERROR
          MDELTA-VAL
          MDELTA
          SIGDELTA-VAL
          SIGDELTA
          ODOM-VAL
          ODOM
))