(cl:defpackage controller_adaptiveclbf-msg
  (:use )
  (:export
   "<DEBUGDATA>"
   "DEBUGDATA"
   "<TRAINMODELACTION>"
   "TRAINMODELACTION"
   "<TRAINMODELACTIONFEEDBACK>"
   "TRAINMODELACTIONFEEDBACK"
   "<TRAINMODELACTIONGOAL>"
   "TRAINMODELACTIONGOAL"
   "<TRAINMODELACTIONRESULT>"
   "TRAINMODELACTIONRESULT"
   "<TRAINMODELFEEDBACK>"
   "TRAINMODELFEEDBACK"
   "<TRAINMODELGOAL>"
   "TRAINMODELGOAL"
   "<TRAINMODELRESULT>"
   "TRAINMODELRESULT"
  ))

