; Auto-generated. Do not edit!


(cl:in-package controller_adaptiveclbf-msg)


;//! \htmlinclude TrainModelResult.msg.html

(cl:defclass <TrainModelResult> (roslisp-msg-protocol:ros-message)
  ((model_trained
    :reader model_trained
    :initarg :model_trained
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass TrainModelResult (<TrainModelResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TrainModelResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TrainModelResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name controller_adaptiveclbf-msg:<TrainModelResult> is deprecated: use controller_adaptiveclbf-msg:TrainModelResult instead.")))

(cl:ensure-generic-function 'model_trained-val :lambda-list '(m))
(cl:defmethod model_trained-val ((m <TrainModelResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader controller_adaptiveclbf-msg:model_trained-val is deprecated.  Use controller_adaptiveclbf-msg:model_trained instead.")
  (model_trained m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TrainModelResult>) ostream)
  "Serializes a message object of type '<TrainModelResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'model_trained) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TrainModelResult>) istream)
  "Deserializes a message object of type '<TrainModelResult>"
    (cl:setf (cl:slot-value msg 'model_trained) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TrainModelResult>)))
  "Returns string type for a message object of type '<TrainModelResult>"
  "controller_adaptiveclbf/TrainModelResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TrainModelResult)))
  "Returns string type for a message object of type 'TrainModelResult"
  "controller_adaptiveclbf/TrainModelResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TrainModelResult>)))
  "Returns md5sum for a message object of type '<TrainModelResult>"
  "188271f01225083e18f9147e2957a5e5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TrainModelResult)))
  "Returns md5sum for a message object of type 'TrainModelResult"
  "188271f01225083e18f9147e2957a5e5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TrainModelResult>)))
  "Returns full string definition for message of type '<TrainModelResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%bool model_trained~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TrainModelResult)))
  "Returns full string definition for message of type 'TrainModelResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%bool model_trained~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TrainModelResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TrainModelResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TrainModelResult
    (cl:cons ':model_trained (model_trained msg))
))
