; Auto-generated. Do not edit!


(cl:in-package controller_adaptiveclbf-msg)


;//! \htmlinclude TrainModelGoal.msg.html

(cl:defclass <TrainModelGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TrainModelGoal (<TrainModelGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TrainModelGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TrainModelGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name controller_adaptiveclbf-msg:<TrainModelGoal> is deprecated: use controller_adaptiveclbf-msg:TrainModelGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TrainModelGoal>) ostream)
  "Serializes a message object of type '<TrainModelGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TrainModelGoal>) istream)
  "Deserializes a message object of type '<TrainModelGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TrainModelGoal>)))
  "Returns string type for a message object of type '<TrainModelGoal>"
  "controller_adaptiveclbf/TrainModelGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TrainModelGoal)))
  "Returns string type for a message object of type 'TrainModelGoal"
  "controller_adaptiveclbf/TrainModelGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TrainModelGoal>)))
  "Returns md5sum for a message object of type '<TrainModelGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TrainModelGoal)))
  "Returns md5sum for a message object of type 'TrainModelGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TrainModelGoal>)))
  "Returns full string definition for message of type '<TrainModelGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TrainModelGoal)))
  "Returns full string definition for message of type 'TrainModelGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TrainModelGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TrainModelGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TrainModelGoal
))
