; Auto-generated. Do not edit!


(cl:in-package controller_adaptiveclbf-msg)


;//! \htmlinclude TrainModelFeedback.msg.html

(cl:defclass <TrainModelFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TrainModelFeedback (<TrainModelFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TrainModelFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TrainModelFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name controller_adaptiveclbf-msg:<TrainModelFeedback> is deprecated: use controller_adaptiveclbf-msg:TrainModelFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TrainModelFeedback>) ostream)
  "Serializes a message object of type '<TrainModelFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TrainModelFeedback>) istream)
  "Deserializes a message object of type '<TrainModelFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TrainModelFeedback>)))
  "Returns string type for a message object of type '<TrainModelFeedback>"
  "controller_adaptiveclbf/TrainModelFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TrainModelFeedback)))
  "Returns string type for a message object of type 'TrainModelFeedback"
  "controller_adaptiveclbf/TrainModelFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TrainModelFeedback>)))
  "Returns md5sum for a message object of type '<TrainModelFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TrainModelFeedback)))
  "Returns md5sum for a message object of type 'TrainModelFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TrainModelFeedback>)))
  "Returns full string definition for message of type '<TrainModelFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TrainModelFeedback)))
  "Returns full string definition for message of type 'TrainModelFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TrainModelFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TrainModelFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TrainModelFeedback
))
